excluded:
  - Pods
  - Carthage
  
disabled_rules: 
  - trailing_whitespace
  - line_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - function_parameter_count
  - identifier_name
  - shorthand_operator
  - discouraged_direct_init

file_length:
  warning: 1000
  error: 1100
  
